### PR TITLE
Move to Python 3 only

### PR DESCRIPTION
**Pull request by bbayles**
Time is short for Python 2. This PR removes `six` and various Python 2-isms. Most of the changes were done by the [pyupgrade](https://github.com/asottile/pyupgrade) module, but I made a few others by hand.

In addition, Travis now exercises the C module.

### CODE REVIEW

**Comment by dw** [comment]
Hi Bo :)

Sorry, gotta reject this one. The culture of ephemerality that grips the Python community (and the modern IT industry at large) is something I simply do not subscribe to. Until such times as a feature becomes absolutely impossible to support because of compatibility concerns, I consider it a mark of craftsmanship to provide software that works regardless of scenario, free of artificial restrictions baked in to support an agenda of forced obsolescence.

I understand this is not a commonly held idea, but it's one I'll never let go of. Thanks for the effort though!

**Comment by dw** [comment]
I'm sorry -- this isn't fair, you have been doing all the work.

Would you like to transfer the repo? He who codes decides! And you're doing all the coding :)

**Comment by bbayles** [comment]
Ha, up to you. I'm happy to maintain a Python 3-only fork. 

I think the last release is probably fine to use in Python 2 indefinitely; this is what I've been doing with my other projects - a final Python 2-compatible release, and then Python 3 only from then on.

**Comment by dw** [comment]
That's a fine idea -- cdb is a nicely non-moving target so this is possible. If you want to go that route, perhaps we should bump the major version number on next PyPI upload.

Thanks again for all your help, and apologies for overreaction -- this is a topic I'm quite heated about :)

**Comment by bbayles** [comment]
I should have changed the major version in this PR, you're right.

I've added the [`python_requires`](https://github.com/dw/python-pure-cdb/pull/25/commits/8c5c0d141779d0326f35a9cc4d028a40d1da01ba#diff-2eeaed663bd0d25b7e608891384b7298R31) keyword to `setup.py`, which will ensure that Python 2 users will get the last version when using `pip`.

This, plus a note on the README and docs index, should make sure everybody can find what they need.

**Comment by dw** [comment]
This is absolutely perfect, go crazy on the merge :)

**Pull request merged**
