### PR TITLE
Re-work Reader class to minimize memory requirements

### PR DESCRIPTION
**Pull request by bbayles**
Re: issue #26, this PR re-works the `Reader` classes such that they no longer require the whole `cdb` file to be in memory.

`Reader` classes now operate on open file objects, and try to minimize both the amount of memory stored and the number of `seek` calls on those file objects.

---

The `Reader` classes can now act as context managers, and can be called one of three ways:

The old way - with the database in memory:
```python
with open('info.cdb', 'rb') as f:
    data = f.read()
reader = cdblib.Reader64(data)
sum(1 for k in set(reader.iterkeys()))
```

Using a file path:
```python
with cdblib.Reader64.from_file_path('info.cdb') as reader:
    sum(1 for k in set(reader.iterkeys()))
```

Using a file object:
```python
with open('info.cdb', 'rb') as f:
    reader = cdblib.Reader64.from_file_obj(file_obj=f)
    sum(1 for k in set(reader.iterkeys()))
```

---

This is a significant re-write, and it's possible I missed some subtlety. However, every CDB file I've tested with behaves properly, and none of the old unit tests needed modification.

After more testing I will release this with a major version number change.

### CODE REVIEW

**Comment by dw** [comment]
I may be mistaken since it's been quite some time, but my understanding was that Reader(data=...) accepted any object that supports substring slicing, including `mmap.mmap`. Except for error handling, there should be little to no advantage for CDBs to use explicit file IO, the result is the same: either a soft fault brings a page into memory, or the read() system call does. Cache usage will be identical in either case

It would be interesting to know how much it effects performance. CDBs are not seek-heavy, so I guess this only amounts to between 3-6 syscalls per lookup

**Comment by dw** [comment]
If you are still experimenting with things, it may additionally be worth trying POSIX_FADV_RANDOM to disable readahead. Linux likes to amplify 4kb random file IO into something like 128kb reads if you trigger the wrong heuristic (which is quite easy IIRC)

**Comment by bbayles** [comment]
Indeed, `mmap` is [recommended in the docs](https://python-pure-cdb.readthedocs.io/en/latest/library.html#limiting-memory-usage).

Error handling was indeed one motivation, a la [this article](https://www.sublimetext.com/blog/articles/use-mmap-with-care).

**Comment by bbayles** [comment]
Since writing this, I noticed that both [DJB's cdb implementation](https://github.com/gyepisam/cdb/blob/c428eff9bccf6baae4a4034052680951b6c051d4/cdb.c#L5) and [python-cdb](https://github.com/acg/python-cdb/blob/c0bad075a04a719f31e6387260b0730c3243fcb1/src/cdb.c#L6) use mmap implicitly. So I'll close this and just add the alternate constructors.

**Pull request closed without merging**
