### PR TITLE
Preparing for a new release (with Python 3 support)

### PR DESCRIPTION
**Pull request by bbayles**
Greetings! I have joined this project as a maintainer (many thanks, @dw). Here is what I've been working on so far.

The big change is the addition of Python 3 support. With the help of `six`, this library now runs on both Python 2 and Python 3.

The other big change is to the organization of the files in the repo. I've created a traditional package structure, which makes for easier installation and testing.

In addition, I've updated `setup.py` to use `setuptools`, added the `cdbmake.py` script to the package installation, and updated the README with some documentation.

---

I'll start filing some issues and opening PRs for these items, but here's a preview of the plan:
* Release a new version with Python 3 support to PyPI
* Add CI testing of commits (with Travis)
* Add code coverage testing (with coveralls)
* Create a nicer interface for storing non-`bytes` data on Python 3
* Add a context manager for the `Writer` classes
* Add more thorough documentation (to ReadTheDocs)
* ...and a few more things.

I'll read through this PR and merge this soon to get started.

### CODE REVIEW

**Comment by dw** [comment]
This all looks great, with one exception - test_ prefix on the filenames. It breaks tab completion and drives me insane :) Other than that please feel free to merge

**Comment by bbayles** [comment]
Hmm, OK. I changed the test file's name.

Note that the `test*.py` file name pattern is needed for the `python -m unittest discover` function to work (see [here](https://github.com/python/cpython/blob/4d193bcc2560b824389e4d98d9d8b9b34e33dbaf/Lib/unittest/loader.py#L240)), but `python setup.py test` still works. (`python -m unittest discover -p "*_test.py"` works also)

**Comment by dw** [comment]
Thanks a ton!

**Comment by bbayles** [comment]
Thank you! I'll ping you about making a release on PyPI after I check a few more things out with Python 3.

**Comment by dw** [comment]
I pushed a commit to port _djb_hash to 3.x, I left the opt-in in place since the name of the package after all is "pure" :)

**Comment by bbayles** [comment]
Ha, that was one of the things I was going to bring up gently a little later.

**Pull request merged**
