### PR TITLE
Sphinx documentation

### PR DESCRIPTION
**Pull request by bbayles**
Re: https://github.com/dw/python-pure-cdb/issues/9, this PR adds a few pages of documentation for the library and CLI tools.

You can see the result [here](https://python-pure-cdb.readthedocs.io/en/new-docs/).

@dw, I think I'll need you (as repo owner) to [add a webhook](https://docs.readthedocs.io/en/latest/webhooks.html#webhook-creation) such that RTD can talk to GitHub? At your leisure, of course.

### CODE REVIEW

**Comment by dw** [comment]
I can't add this without some "ID" component in the URL. Would you please add 'dw' to the project admins list on RTFD

**Comment by bbayles** [comment]
I've added a maintainer; hopefully that does the trick.

**Comment by dw** [comment]
Looks like it's all setup now. Thanks a ton for this!

**Comment by dw** [comment]
Holy cow - I only got a chance to thoroughly look through this, it is amazing work! Thanks again

**Pull request merged**
